// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk1POEpLDdYhqXevoKzrL8nNgamajCyUw',
    appId: '1:522224904931:web:13cd953ff173c6368073d6',
    messagingSenderId: '522224904931',
    projectId: 'aquafilev2',
    authDomain: 'aquafilev2.firebaseapp.com',
    storageBucket: 'aquafilev2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZs2p6rGK_IsUFKeV_5aqyuPwAuN0bZ9E',
    appId: '1:522224904931:android:e1b03ae53cb3708a8073d6',
    messagingSenderId: '522224904931',
    projectId: 'aquafilev2',
    storageBucket: 'aquafilev2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5oJYrT9pEhCdc7AZ8y2Ll8GgOGRxcXBo',
    appId: '1:522224904931:ios:b57ef1fd89ad97d68073d6',
    messagingSenderId: '522224904931',
    projectId: 'aquafilev2',
    storageBucket: 'aquafilev2.appspot.com',
    iosBundleId: 'com.example.aquafile2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5oJYrT9pEhCdc7AZ8y2Ll8GgOGRxcXBo',
    appId: '1:522224904931:ios:b57ef1fd89ad97d68073d6',
    messagingSenderId: '522224904931',
    projectId: 'aquafilev2',
    storageBucket: 'aquafilev2.appspot.com',
    iosBundleId: 'com.example.aquafile2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk1POEpLDdYhqXevoKzrL8nNgamajCyUw',
    appId: '1:522224904931:web:39b6209099ae00688073d6',
    messagingSenderId: '522224904931',
    projectId: 'aquafilev2',
    authDomain: 'aquafilev2.firebaseapp.com',
    storageBucket: 'aquafilev2.appspot.com',
  );
}
